// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	AddTemplateVersionQuestion(ctx context.Context, arg AddTemplateVersionQuestionParams) (TemplateVersionQuestion, error)
	CreateQuestionVersion(ctx context.Context, arg CreateQuestionVersionParams) (QuestionVersion, error)
	CreateRegulatoryReferenceVersion(ctx context.Context, arg CreateRegulatoryReferenceVersionParams) (RegulatoryReferenceVersion, error)
	CreateReportDefinitionVersion(ctx context.Context, arg CreateReportDefinitionVersionParams) (ReportDefinitionVersion, error)
	CreateTemplateMaster(ctx context.Context, arg CreateTemplateMasterParams) (CreateTemplateMasterRow, error)
	CreateUserLifecycleRequest(ctx context.Context, arg CreateUserLifecycleRequestParams) (CreateUserLifecycleRequestRow, error)
	GetTemplateMaster(ctx context.Context, id string) (GetTemplateMasterRow, error)
	GetUserLifecycleRequestByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetUserLifecycleRequestByIdempotencyKeyRow, error)
	ListAccessDirectoryLocalStates(ctx context.Context, subjectIds []string) ([]ListAccessDirectoryLocalStatesRow, error)
	ListQuestionVersions(ctx context.Context, limit int32) ([]QuestionVersion, error)
	ListRegulatoryReferenceVersions(ctx context.Context, arg ListRegulatoryReferenceVersionsParams) ([]RegulatoryReferenceVersion, error)
	ListReportDefinitionVersions(ctx context.Context, limit int32) ([]ReportDefinitionVersion, error)
	ListTemplateMasters(ctx context.Context, limit int32) ([]ListTemplateMastersRow, error)
	ListUserLifecycleRequests(ctx context.Context, arg ListUserLifecycleRequestsParams) ([]ListUserLifecycleRequestsRow, error)
	UpdateUserLifecycleRequest(ctx context.Context, arg UpdateUserLifecycleRequestParams) (UpdateUserLifecycleRequestRow, error)
}

var _ Querier = (*Queries)(nil)
