// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTemplateVersionQuestion = `-- name: AddTemplateVersionQuestion :one
INSERT INTO template_version_questions (
    template_version_id, question_version_id, position
) VALUES ($1, $2, $3)
RETURNING template_version_id, question_version_id, position, created_at
`

type AddTemplateVersionQuestionParams struct {
	TemplateVersionID string `json:"template_version_id"`
	QuestionVersionID string `json:"question_version_id"`
	Position          int32  `json:"position"`
}

func (q *Queries) AddTemplateVersionQuestion(ctx context.Context, arg AddTemplateVersionQuestionParams) (TemplateVersionQuestion, error) {
	row := q.db.QueryRow(ctx, addTemplateVersionQuestion, arg.TemplateVersionID, arg.QuestionVersionID, arg.Position)
	var i TemplateVersionQuestion
	err := row.Scan(
		&i.TemplateVersionID,
		&i.QuestionVersionID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createQuestionVersion = `-- name: CreateQuestionVersion :one
INSERT INTO question_versions (
    id, question_id, version, prompt, configured_reference,
    expected_evidence, created_by_subject_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, question_id, version, prompt, configured_reference,
          expected_evidence, created_by_subject_id, created_at
`

type CreateQuestionVersionParams struct {
	ID                  string `json:"id"`
	QuestionID          string `json:"question_id"`
	Version             int32  `json:"version"`
	Prompt              string `json:"prompt"`
	ConfiguredReference string `json:"configured_reference"`
	ExpectedEvidence    string `json:"expected_evidence"`
	CreatedBySubjectID  string `json:"created_by_subject_id"`
}

func (q *Queries) CreateQuestionVersion(ctx context.Context, arg CreateQuestionVersionParams) (QuestionVersion, error) {
	row := q.db.QueryRow(ctx, createQuestionVersion,
		arg.ID,
		arg.QuestionID,
		arg.Version,
		arg.Prompt,
		arg.ConfiguredReference,
		arg.ExpectedEvidence,
		arg.CreatedBySubjectID,
	)
	var i QuestionVersion
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Version,
		&i.Prompt,
		&i.ConfiguredReference,
		&i.ExpectedEvidence,
		&i.CreatedBySubjectID,
		&i.CreatedAt,
	)
	return i, err
}

const createRegulatoryReferenceVersion = `-- name: CreateRegulatoryReferenceVersion :one
INSERT INTO regulatory_reference_versions (
    id, reference_id, version, title, status, effective_date, snapshot
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, reference_id, version, title, status, effective_date, snapshot, created_at
`

type CreateRegulatoryReferenceVersionParams struct {
	ID            string      `json:"id"`
	ReferenceID   string      `json:"reference_id"`
	Version       int32       `json:"version"`
	Title         string      `json:"title"`
	Status        string      `json:"status"`
	EffectiveDate pgtype.Date `json:"effective_date"`
	Snapshot      []byte      `json:"snapshot"`
}

func (q *Queries) CreateRegulatoryReferenceVersion(ctx context.Context, arg CreateRegulatoryReferenceVersionParams) (RegulatoryReferenceVersion, error) {
	row := q.db.QueryRow(ctx, createRegulatoryReferenceVersion,
		arg.ID,
		arg.ReferenceID,
		arg.Version,
		arg.Title,
		arg.Status,
		arg.EffectiveDate,
		arg.Snapshot,
	)
	var i RegulatoryReferenceVersion
	err := row.Scan(
		&i.ID,
		&i.ReferenceID,
		&i.Version,
		&i.Title,
		&i.Status,
		&i.EffectiveDate,
		&i.Snapshot,
		&i.CreatedAt,
	)
	return i, err
}

const createReportDefinitionVersion = `-- name: CreateReportDefinitionVersion :one
INSERT INTO report_definition_versions (
    id, definition_id, version, title, description, definition,
    created_by_subject_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, definition_id, version, title, description, definition,
          created_by_subject_id, created_at
`

type CreateReportDefinitionVersionParams struct {
	ID                 string `json:"id"`
	DefinitionID       string `json:"definition_id"`
	Version            int32  `json:"version"`
	Title              string `json:"title"`
	Description        string `json:"description"`
	Definition         []byte `json:"definition"`
	CreatedBySubjectID string `json:"created_by_subject_id"`
}

func (q *Queries) CreateReportDefinitionVersion(ctx context.Context, arg CreateReportDefinitionVersionParams) (ReportDefinitionVersion, error) {
	row := q.db.QueryRow(ctx, createReportDefinitionVersion,
		arg.ID,
		arg.DefinitionID,
		arg.Version,
		arg.Title,
		arg.Description,
		arg.Definition,
		arg.CreatedBySubjectID,
	)
	var i ReportDefinitionVersion
	err := row.Scan(
		&i.ID,
		&i.DefinitionID,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.Definition,
		&i.CreatedBySubjectID,
		&i.CreatedAt,
	)
	return i, err
}

const createTemplateMaster = `-- name: CreateTemplateMaster :one
INSERT INTO template_masters (
    id, title, owner_role, published_template_version_id, revision
) VALUES ($1, $2, $3, $4, 1)
RETURNING id, title, owner_role, published_template_version_id, revision,
          created_at, updated_at
`

type CreateTemplateMasterParams struct {
	ID                         string  `json:"id"`
	Title                      string  `json:"title"`
	OwnerRole                  string  `json:"owner_role"`
	PublishedTemplateVersionID *string `json:"published_template_version_id"`
}

type CreateTemplateMasterRow struct {
	ID                         string             `json:"id"`
	Title                      string             `json:"title"`
	OwnerRole                  string             `json:"owner_role"`
	PublishedTemplateVersionID *string            `json:"published_template_version_id"`
	Revision                   int64              `json:"revision"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTemplateMaster(ctx context.Context, arg CreateTemplateMasterParams) (CreateTemplateMasterRow, error) {
	row := q.db.QueryRow(ctx, createTemplateMaster,
		arg.ID,
		arg.Title,
		arg.OwnerRole,
		arg.PublishedTemplateVersionID,
	)
	var i CreateTemplateMasterRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.OwnerRole,
		&i.PublishedTemplateVersionID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserLifecycleRequest = `-- name: CreateUserLifecycleRequest :one
INSERT INTO user_lifecycle_requests (
    id, subject_id, requested_action, requested_roles,
    requested_organization_id, requested_email, requested_display_name,
    status, idempotency_key, requested_by_subject_id, outbox_message_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, 'PENDING', $8, $9, $10)
RETURNING id, subject_id, requested_action, requested_roles,
          requested_organization_id, requested_email, requested_display_name,
          status, idempotency_key,
          requested_by_subject_id, outbox_message_id, failure_reason,
          created_at, updated_at
`

type CreateUserLifecycleRequestParams struct {
	ID                      string   `json:"id"`
	SubjectID               *string  `json:"subject_id"`
	RequestedAction         string   `json:"requested_action"`
	RequestedRoles          []string `json:"requested_roles"`
	RequestedOrganizationID *string  `json:"requested_organization_id"`
	RequestedEmail          *string  `json:"requested_email"`
	RequestedDisplayName    *string  `json:"requested_display_name"`
	IdempotencyKey          string   `json:"idempotency_key"`
	RequestedBySubjectID    string   `json:"requested_by_subject_id"`
	OutboxMessageID         *string  `json:"outbox_message_id"`
}

type CreateUserLifecycleRequestRow struct {
	ID                      string             `json:"id"`
	SubjectID               *string            `json:"subject_id"`
	RequestedAction         string             `json:"requested_action"`
	RequestedRoles          []string           `json:"requested_roles"`
	RequestedOrganizationID *string            `json:"requested_organization_id"`
	RequestedEmail          *string            `json:"requested_email"`
	RequestedDisplayName    *string            `json:"requested_display_name"`
	Status                  string             `json:"status"`
	IdempotencyKey          string             `json:"idempotency_key"`
	RequestedBySubjectID    string             `json:"requested_by_subject_id"`
	OutboxMessageID         *string            `json:"outbox_message_id"`
	FailureReason           *string            `json:"failure_reason"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUserLifecycleRequest(ctx context.Context, arg CreateUserLifecycleRequestParams) (CreateUserLifecycleRequestRow, error) {
	row := q.db.QueryRow(ctx, createUserLifecycleRequest,
		arg.ID,
		arg.SubjectID,
		arg.RequestedAction,
		arg.RequestedRoles,
		arg.RequestedOrganizationID,
		arg.RequestedEmail,
		arg.RequestedDisplayName,
		arg.IdempotencyKey,
		arg.RequestedBySubjectID,
		arg.OutboxMessageID,
	)
	var i CreateUserLifecycleRequestRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.RequestedAction,
		&i.RequestedRoles,
		&i.RequestedOrganizationID,
		&i.RequestedEmail,
		&i.RequestedDisplayName,
		&i.Status,
		&i.IdempotencyKey,
		&i.RequestedBySubjectID,
		&i.OutboxMessageID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateMaster = `-- name: GetTemplateMaster :one
SELECT id, title, owner_role, published_template_version_id, revision,
       created_at, updated_at
FROM template_masters
WHERE id = $1 AND tombstoned_at IS NULL
`

type GetTemplateMasterRow struct {
	ID                         string             `json:"id"`
	Title                      string             `json:"title"`
	OwnerRole                  string             `json:"owner_role"`
	PublishedTemplateVersionID *string            `json:"published_template_version_id"`
	Revision                   int64              `json:"revision"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTemplateMaster(ctx context.Context, id string) (GetTemplateMasterRow, error) {
	row := q.db.QueryRow(ctx, getTemplateMaster, id)
	var i GetTemplateMasterRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.OwnerRole,
		&i.PublishedTemplateVersionID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserLifecycleRequestByIdempotencyKey = `-- name: GetUserLifecycleRequestByIdempotencyKey :one
SELECT id, subject_id, requested_action, requested_roles,
       requested_organization_id, requested_email, requested_display_name,
       status, idempotency_key,
       requested_by_subject_id, outbox_message_id, failure_reason,
       created_at, updated_at
FROM user_lifecycle_requests
WHERE idempotency_key = $1
`

type GetUserLifecycleRequestByIdempotencyKeyRow struct {
	ID                      string             `json:"id"`
	SubjectID               *string            `json:"subject_id"`
	RequestedAction         string             `json:"requested_action"`
	RequestedRoles          []string           `json:"requested_roles"`
	RequestedOrganizationID *string            `json:"requested_organization_id"`
	RequestedEmail          *string            `json:"requested_email"`
	RequestedDisplayName    *string            `json:"requested_display_name"`
	Status                  string             `json:"status"`
	IdempotencyKey          string             `json:"idempotency_key"`
	RequestedBySubjectID    string             `json:"requested_by_subject_id"`
	OutboxMessageID         *string            `json:"outbox_message_id"`
	FailureReason           *string            `json:"failure_reason"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserLifecycleRequestByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetUserLifecycleRequestByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserLifecycleRequestByIdempotencyKey, idempotencyKey)
	var i GetUserLifecycleRequestByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.RequestedAction,
		&i.RequestedRoles,
		&i.RequestedOrganizationID,
		&i.RequestedEmail,
		&i.RequestedDisplayName,
		&i.Status,
		&i.IdempotencyKey,
		&i.RequestedBySubjectID,
		&i.OutboxMessageID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccessDirectoryLocalStates = `-- name: ListAccessDirectoryLocalStates :many
WITH latest_membership AS (
    SELECT DISTINCT ON (subject_id)
        membership_id, subject_id, revision, membership_state,
        organization_id, roles, drift_state
    FROM desired_membership_versions
    ORDER BY subject_id, revision DESC
),
latest_lifecycle AS (
    SELECT DISTINCT ON (subject_id)
        id, subject_id, requested_action, status
    FROM user_lifecycle_requests
    WHERE subject_id IS NOT NULL
    ORDER BY subject_id, updated_at DESC, id DESC
),
last_session AS (
    SELECT subject_id, MAX(last_seen_at) AS last_seen_at
    FROM session_references
    GROUP BY subject_id
)
SELECT identity.subject_id,
       (profile.subject_id IS NOT NULL)::boolean AS profile_linked,
       COALESCE(membership.membership_id, '') AS membership_id,
       COALESCE(membership.revision, 0)::bigint AS membership_revision,
       COALESCE(membership.membership_state, 'ABSENT') AS membership_state,
       COALESCE(membership.organization_id, '') AS organization_id,
       COALESCE(membership.roles, ARRAY[]::text[])::text[] AS roles,
       COALESCE(membership.drift_state, 'UNTRACKED') AS stored_drift,
       COALESCE(lifecycle.requested_action, '') AS lifecycle_action,
       COALESCE(lifecycle.status, '') AS lifecycle_status,
       COALESCE(invitation_delivery.status, '') AS invitation_delivery_status,
       last_session.last_seen_at::timestamptz AS last_successful_session
FROM identity_references identity
LEFT JOIN user_profiles profile
  ON profile.subject_id = identity.subject_id
LEFT JOIN latest_membership membership
  ON membership.subject_id = identity.subject_id
LEFT JOIN latest_lifecycle lifecycle
  ON lifecycle.subject_id = identity.subject_id
LEFT JOIN LATERAL (
    SELECT job.status
    FROM notification_records record
    JOIN notification_delivery_jobs job
      ON job.notification_id = record.id
     AND job.recipient_subject_id = identity.subject_id
     AND job.channel = 'EMAIL'
    WHERE record.recipient_subject_id = identity.subject_id
      AND record.related_entity_type = 'USER_LIFECYCLE_INVITATION'
      AND record.related_entity_id = lifecycle.id
      AND record.tombstoned_at IS NULL
    ORDER BY job.created_at DESC, job.id DESC
    LIMIT 1
) invitation_delivery ON TRUE
LEFT JOIN last_session
  ON last_session.subject_id = identity.subject_id
WHERE identity.subject_id = ANY($1::text[])
  AND identity.tombstoned_at IS NULL
ORDER BY identity.subject_id
`

type ListAccessDirectoryLocalStatesRow struct {
	SubjectID                string             `json:"subject_id"`
	ProfileLinked            bool               `json:"profile_linked"`
	MembershipID             string             `json:"membership_id"`
	MembershipRevision       int64              `json:"membership_revision"`
	MembershipState          string             `json:"membership_state"`
	OrganizationID           string             `json:"organization_id"`
	Roles                    []string           `json:"roles"`
	StoredDrift              string             `json:"stored_drift"`
	LifecycleAction          string             `json:"lifecycle_action"`
	LifecycleStatus          string             `json:"lifecycle_status"`
	InvitationDeliveryStatus string             `json:"invitation_delivery_status"`
	LastSuccessfulSession    pgtype.Timestamptz `json:"last_successful_session"`
}

func (q *Queries) ListAccessDirectoryLocalStates(ctx context.Context, subjectIds []string) ([]ListAccessDirectoryLocalStatesRow, error) {
	rows, err := q.db.Query(ctx, listAccessDirectoryLocalStates, subjectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessDirectoryLocalStatesRow
	for rows.Next() {
		var i ListAccessDirectoryLocalStatesRow
		if err := rows.Scan(
			&i.SubjectID,
			&i.ProfileLinked,
			&i.MembershipID,
			&i.MembershipRevision,
			&i.MembershipState,
			&i.OrganizationID,
			&i.Roles,
			&i.StoredDrift,
			&i.LifecycleAction,
			&i.LifecycleStatus,
			&i.InvitationDeliveryStatus,
			&i.LastSuccessfulSession,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionVersions = `-- name: ListQuestionVersions :many
SELECT id, question_id, version, prompt, configured_reference,
       expected_evidence, created_by_subject_id, created_at
FROM question_versions
ORDER BY question_id, version DESC
LIMIT $1
`

func (q *Queries) ListQuestionVersions(ctx context.Context, limit int32) ([]QuestionVersion, error) {
	rows, err := q.db.Query(ctx, listQuestionVersions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionVersion
	for rows.Next() {
		var i QuestionVersion
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Version,
			&i.Prompt,
			&i.ConfiguredReference,
			&i.ExpectedEvidence,
			&i.CreatedBySubjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegulatoryReferenceVersions = `-- name: ListRegulatoryReferenceVersions :many
SELECT id, reference_id, version, title, status, effective_date, snapshot, created_at
FROM regulatory_reference_versions
WHERE ($1::text = '' OR status = $1::text)
ORDER BY effective_date DESC, reference_id, version DESC
LIMIT $2
`

type ListRegulatoryReferenceVersionsParams struct {
	StatusFilter string `json:"status_filter"`
	ResultLimit  int32  `json:"result_limit"`
}

func (q *Queries) ListRegulatoryReferenceVersions(ctx context.Context, arg ListRegulatoryReferenceVersionsParams) ([]RegulatoryReferenceVersion, error) {
	rows, err := q.db.Query(ctx, listRegulatoryReferenceVersions, arg.StatusFilter, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegulatoryReferenceVersion
	for rows.Next() {
		var i RegulatoryReferenceVersion
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceID,
			&i.Version,
			&i.Title,
			&i.Status,
			&i.EffectiveDate,
			&i.Snapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportDefinitionVersions = `-- name: ListReportDefinitionVersions :many
SELECT id, definition_id, version, title, description, definition,
       created_by_subject_id, created_at
FROM report_definition_versions
ORDER BY definition_id, version DESC
LIMIT $1
`

func (q *Queries) ListReportDefinitionVersions(ctx context.Context, limit int32) ([]ReportDefinitionVersion, error) {
	rows, err := q.db.Query(ctx, listReportDefinitionVersions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReportDefinitionVersion
	for rows.Next() {
		var i ReportDefinitionVersion
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.Definition,
			&i.CreatedBySubjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateMasters = `-- name: ListTemplateMasters :many
SELECT id, title, owner_role, published_template_version_id, revision,
       created_at, updated_at
FROM template_masters
WHERE tombstoned_at IS NULL
ORDER BY title, id
LIMIT $1
`

type ListTemplateMastersRow struct {
	ID                         string             `json:"id"`
	Title                      string             `json:"title"`
	OwnerRole                  string             `json:"owner_role"`
	PublishedTemplateVersionID *string            `json:"published_template_version_id"`
	Revision                   int64              `json:"revision"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTemplateMasters(ctx context.Context, limit int32) ([]ListTemplateMastersRow, error) {
	rows, err := q.db.Query(ctx, listTemplateMasters, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTemplateMastersRow
	for rows.Next() {
		var i ListTemplateMastersRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OwnerRole,
			&i.PublishedTemplateVersionID,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLifecycleRequests = `-- name: ListUserLifecycleRequests :many
SELECT id, subject_id, requested_action, requested_roles,
       requested_organization_id, requested_email, requested_display_name,
       status, idempotency_key,
       requested_by_subject_id, outbox_message_id, failure_reason,
       created_at, updated_at
FROM user_lifecycle_requests
WHERE ($1::text = '' OR status = $1::text)
ORDER BY created_at, id
LIMIT $2
`

type ListUserLifecycleRequestsParams struct {
	StatusFilter string `json:"status_filter"`
	ResultLimit  int32  `json:"result_limit"`
}

type ListUserLifecycleRequestsRow struct {
	ID                      string             `json:"id"`
	SubjectID               *string            `json:"subject_id"`
	RequestedAction         string             `json:"requested_action"`
	RequestedRoles          []string           `json:"requested_roles"`
	RequestedOrganizationID *string            `json:"requested_organization_id"`
	RequestedEmail          *string            `json:"requested_email"`
	RequestedDisplayName    *string            `json:"requested_display_name"`
	Status                  string             `json:"status"`
	IdempotencyKey          string             `json:"idempotency_key"`
	RequestedBySubjectID    string             `json:"requested_by_subject_id"`
	OutboxMessageID         *string            `json:"outbox_message_id"`
	FailureReason           *string            `json:"failure_reason"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUserLifecycleRequests(ctx context.Context, arg ListUserLifecycleRequestsParams) ([]ListUserLifecycleRequestsRow, error) {
	rows, err := q.db.Query(ctx, listUserLifecycleRequests, arg.StatusFilter, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserLifecycleRequestsRow
	for rows.Next() {
		var i ListUserLifecycleRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.RequestedAction,
			&i.RequestedRoles,
			&i.RequestedOrganizationID,
			&i.RequestedEmail,
			&i.RequestedDisplayName,
			&i.Status,
			&i.IdempotencyKey,
			&i.RequestedBySubjectID,
			&i.OutboxMessageID,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLifecycleRequest = `-- name: UpdateUserLifecycleRequest :one
UPDATE user_lifecycle_requests
SET status = $2,
    failure_reason = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, subject_id, requested_action, requested_roles,
          requested_organization_id, requested_email, requested_display_name,
          status, idempotency_key,
          requested_by_subject_id, outbox_message_id, failure_reason,
          created_at, updated_at
`

type UpdateUserLifecycleRequestParams struct {
	ID            string             `json:"id"`
	Status        string             `json:"status"`
	FailureReason *string            `json:"failure_reason"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UpdateUserLifecycleRequestRow struct {
	ID                      string             `json:"id"`
	SubjectID               *string            `json:"subject_id"`
	RequestedAction         string             `json:"requested_action"`
	RequestedRoles          []string           `json:"requested_roles"`
	RequestedOrganizationID *string            `json:"requested_organization_id"`
	RequestedEmail          *string            `json:"requested_email"`
	RequestedDisplayName    *string            `json:"requested_display_name"`
	Status                  string             `json:"status"`
	IdempotencyKey          string             `json:"idempotency_key"`
	RequestedBySubjectID    string             `json:"requested_by_subject_id"`
	OutboxMessageID         *string            `json:"outbox_message_id"`
	FailureReason           *string            `json:"failure_reason"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserLifecycleRequest(ctx context.Context, arg UpdateUserLifecycleRequestParams) (UpdateUserLifecycleRequestRow, error) {
	row := q.db.QueryRow(ctx, updateUserLifecycleRequest,
		arg.ID,
		arg.Status,
		arg.FailureReason,
		arg.UpdatedAt,
	)
	var i UpdateUserLifecycleRequestRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.RequestedAction,
		&i.RequestedRoles,
		&i.RequestedOrganizationID,
		&i.RequestedEmail,
		&i.RequestedDisplayName,
		&i.Status,
		&i.IdempotencyKey,
		&i.RequestedBySubjectID,
		&i.OutboxMessageID,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
