DO $$
DECLARE table_name text; has_records boolean;
BEGIN
 FOREACH table_name IN ARRAY ARRAY['caa_departments','caa_organizational_units','caa_department_status_facts','caa_organizational_unit_status_facts','service_provider_types','service_provider_topics','service_provider_topic_links','service_provider_unit_responsibilities','caa_department_memberships','organization_service_provider_scope_targets','organization_service_provider_scopes','regulated_targets','regulatory_source_versions','regulatory_normalized_clauses','regulatory_source_gap_facts','state_compliance_crosswalk_rows','regulatory_evaluations','regulatory_evaluation_partitions','regulatory_evaluation_partition_rows','regulatory_generation_runs','regulatory_generation_run_scope_facts','regulatory_generation_run_source_snapshots','regulatory_generation_run_crosswalk_partition_rows','regulatory_generated_mapping_snapshots','regulatory_generated_question_snapshots','candidate_required_owner_assignments','department_review_decisions','checklist_publication_decisions','governed_candidate_commands','audit_package_governance_snapshots'] LOOP
  IF to_regclass('public.' || table_name) IS NOT NULL THEN
   IF table_name IN ('caa_departments','caa_organizational_units','caa_department_status_facts','caa_organizational_unit_status_facts','service_provider_types','service_provider_topics','service_provider_topic_links','service_provider_unit_responsibilities') THEN EXECUTE format('SELECT EXISTS (SELECT 1 FROM %I WHERE NOT baseline_seed LIMIT 1)', table_name) INTO has_records;
   ELSIF table_name = 'regulatory_source_versions' THEN SELECT EXISTS (SELECT 1 FROM regulatory_source_versions WHERE id <> 'NCAA-CC-ANNEX6-PARTI-A610-SUPPLIED-2026-07-28') INTO has_records;
   ELSIF table_name = 'regulatory_normalized_clauses' THEN SELECT EXISTS (SELECT 1 FROM regulatory_normalized_clauses WHERE id NOT IN ('NCAA-CC-A610-4.2.2.2','NCAA-CC-A610-4.2.12.1','NCAA-CC-A610-6.2.2','NCAA-CC-A610-6.16','NCAA-CC-A610-8.1.1')) INTO has_records;
   ELSIF table_name = 'state_compliance_crosswalk_rows' THEN SELECT EXISTS (SELECT 1 FROM state_compliance_crosswalk_rows WHERE id NOT IN ('NCAA-CC-A610-ROW-4.2.2.2','NCAA-CC-A610-ROW-4.2.12.1','NCAA-CC-A610-ROW-6.2.2','NCAA-CC-A610-ROW-6.16','NCAA-CC-A610-ROW-8.1.1')) INTO has_records;
   ELSE EXECUTE format('SELECT EXISTS (SELECT 1 FROM %I LIMIT 1)', table_name) INTO has_records; END IF;
  ELSE has_records := false; END IF;
  IF has_records THEN RAISE EXCEPTION 'migration 21 rollback refused: governed records exist in %', table_name; END IF;
 END LOOP;
END;
$$;
DROP TRIGGER checklist_template_versions_governed_publication_guard ON checklist_template_versions;
DROP TRIGGER template_draft_versions_generated_immutable ON template_draft_versions;
DROP TRIGGER template_draft_versions_generated_lineage_guard ON template_draft_versions;
DROP TRIGGER governed_candidate_commands_append_only ON governed_candidate_commands;
DROP TRIGGER regulatory_source_gap_facts_append_only ON regulatory_source_gap_facts;
ALTER TABLE checklist_template_versions DROP CONSTRAINT checklist_template_versions_governed_publication_shape;
ALTER TABLE checklist_template_versions DROP COLUMN publication_decision_id;
ALTER TABLE checklist_template_versions DROP COLUMN candidate_content_digest;
ALTER TABLE checklist_template_versions DROP COLUMN candidate_revision;
ALTER TABLE checklist_template_versions DROP COLUMN candidate_draft_version_id;
DROP TABLE checklist_publication_decisions;
DROP TABLE department_review_decisions;
DROP TABLE governed_candidate_commands;
DROP TABLE candidate_required_owner_assignments;
ALTER TABLE template_draft_versions DROP CONSTRAINT template_draft_versions_candidate_root_check;
ALTER TABLE template_draft_versions DROP COLUMN supersedes_candidate_id;
ALTER TABLE template_draft_versions DROP COLUMN candidate_root_id;
ALTER TABLE template_draft_versions DROP CONSTRAINT template_draft_versions_candidate_identity_unique;
ALTER TABLE template_draft_versions DROP CONSTRAINT template_draft_versions_generated_lineage_check;
ALTER TABLE template_draft_versions DROP COLUMN candidate_schema_version;
ALTER TABLE template_draft_versions DROP COLUMN candidate_content_digest;
ALTER TABLE template_draft_versions DROP COLUMN generation_run_id;
ALTER TABLE template_draft_versions DROP CONSTRAINT template_draft_versions_status_check;
ALTER TABLE template_draft_versions ADD CONSTRAINT template_draft_versions_status_check CHECK (status = 'DRAFT');
DROP TABLE regulatory_generated_question_snapshots;
DROP TABLE regulatory_generated_mapping_snapshots;
DROP TABLE regulatory_generation_run_crosswalk_partition_rows;
DROP TABLE regulatory_generation_run_source_snapshots;
DROP TABLE regulatory_generation_run_scope_facts;
DROP TABLE regulatory_generation_runs;
DROP TABLE regulatory_evaluation_partition_rows;
DROP TABLE regulatory_evaluation_partitions;
DROP TABLE regulatory_evaluations;
DROP TABLE regulatory_source_gap_facts;
DROP TABLE state_compliance_crosswalk_rows;
DROP TABLE regulatory_normalized_clauses;
DROP TABLE regulatory_source_versions;
DROP TABLE organization_service_provider_scope_targets;
DROP TABLE organization_service_provider_scopes;
DROP TABLE regulated_targets;
DROP TABLE service_provider_unit_responsibilities;
DROP TABLE service_provider_topic_links;
DROP TABLE service_provider_topics;
DROP TABLE service_provider_types;
DROP TABLE caa_department_memberships;
DROP TABLE caa_organizational_unit_status_facts;
DROP TABLE caa_department_status_facts;
DROP TABLE caa_organizational_units;
DROP TABLE caa_departments;
DROP FUNCTION validate_governed_scope_primary_target();
DROP FUNCTION validate_governed_scope_target();
DROP FUNCTION governed_status_successor_guard();
DROP FUNCTION governed_successor_guard();
DROP FUNCTION governed_baseline_seed_guard();
DROP FUNCTION governed_append_only_guard();
DROP FUNCTION validate_governed_published_template();
DROP FUNCTION validate_governed_publication_approval();
DROP FUNCTION validate_governed_decision_actor();
DROP FUNCTION validate_governed_generated_candidate();
DROP FUNCTION validate_governed_generation_scope_fact();
DROP FUNCTION governed_generated_candidate_immutable_guard();
DROP FUNCTION validate_governed_generation_snapshot();
DROP FUNCTION validate_governed_partition_identity();
DROP FUNCTION validate_governed_crosswalk_row();
DROP FUNCTION validate_governed_clause_source_hash();
DROP FUNCTION governed_jsonb_sha256(jsonb);
DROP FUNCTION governed_sha256(text);
DELETE FROM schema_migrations WHERE version = 21;
