import type { GovernedCandidateBundleInput, GovernedGenerationRequestInput } from "./backend";

export const SYNTHETIC_SOURCE_HASH = "sha256:1111111111111111111111111111111111111111111111111111111111111111";
export const SYNTHETIC_INPUT_DIGEST = "sha256:16263c98748063fc7e29dbb7744189cf9a81fd635bed641579772bafa70a6d64";
export const SYNTHETIC_OUTPUT_DIGEST = "sha256:377598cb1bee5388b19c9d7d4de34f1ff9f6b16b7ac1d2ff6cc5d96af798ad19";
export const SYNTHETIC_EDITED_RATIONALE = "Synthetic test-profile rationale reviewed by an Admin without changing the controlled source claim.";
export const SYNTHETIC_FAILED_RUN_ID = "GENRUN-FAILED-SYNTHETIC-INSPECTION";
export const SYNTHETIC_FAILED_REQUEST_ID = "GENREQ-FAILED-SYNTHETIC-INSPECTION";

export const EXACT_BLOCKED_REAL_OPS_AOC_REQUEST: GovernedGenerationRequestInput = {
  schemaVersion: "1.0.0",
  requestId: "GENREQ-OPS-AOC-0001",
  organizationId: "ORG-FLY-NAMIBIA",
  serviceProviderScopeFactIds: ["SCOPE-OPS-AOC-SOURCE-BOUND"],
  serviceProviderTypes: ["AIR_OPERATOR"],
  providerCatalogVersion: "1.0.0",
  inspectionType: "RAMP_INSPECTION",
  target: { targetId: "TARGET-OPS-AOC-SOURCE-BOUND", kind: "ORGANIZATION" },
  sourceSnapshots: [{
    sourceSnapshotId: "NCAA-CC-ANNEX6-PARTI-A610-SUPPLIED-2026-07-28",
    sourceHash: "sha256:13fe82d1767320443f91ed61cf7d3b4bba0ea24f217fad45bbd9cae5fc682af2",
    clauseIds: ["NCAA-CC-A610-4.2.2.2"],
    clauseLocators: ["Annex 6 Part I 4.2.2.2"],
  }],
  secondaryCrosswalkPartition: {
    partitionId: "CC-OPS-TRAIN-1",
    stableRowIds: ["CC:NAMB:ANNEX6:4.2.2.2"],
  },
  unresolvedSourceGaps: [{
    gapId: "CONTROLLED_PROCEDURE",
    reason: "The controlled NCAA Operations surveillance/ramp-inspection procedure has not been supplied.",
  }, {
    gapId: "PART_140_AUTHORITY",
    reason: "Current Part 140 authority and supersession require source-owner confirmation.",
  }, {
    gapId: "PART_127_APPLICABILITY",
    reason: "Exact Part 127 operation/configuration applicability requires Department Manager confirmation.",
  }, {
    gapId: "AMBIGUOUS_OWNERSHIP",
    reason: "Exact source ownership and controlled-procedure stewardship remain unresolved.",
  }],
  generationPolicyVersion: "regulatory-checklist-v1",
  providerId: "imported-result-only",
  providerVersion: "1.0.0",
  requestedOutputs: ["COMPLIANCE_MAPPING", "INSPECTION_CHECKLIST"],
  canonicalInputDigest: "sha256:e0231ec606fc59adfe5a425674bc4b3130b92e1df70df22ee666cc4ba7d91583",
};

export const SYNTHETIC_GOVERNED_BUNDLE: GovernedCandidateBundleInput = {
  schemaVersion: "1.0.0",
  candidateBundleId: "CAND-SYNTHETIC-OPS-AOC-0001",
  generationRunId: "GENRUN-SYNTHETIC-OPS-AOC-0001",
  status: "GENERATED_DRAFT",
  generationRequest: {
    schemaVersion: "1.0.0",
    requestId: "GENREQ-SYNTHETIC-OPS-AOC-0001",
    organizationId: "ORG-SYNTHETIC-AOC",
    serviceProviderScopeFactIds: ["SCOPE-SYNTHETIC-AOC"],
    serviceProviderTypes: ["AIR_OPERATOR"],
    providerCatalogVersion: "1.0.0",
    inspectionType: "RAMP_INSPECTION",
    target: { targetId: "TARGET-SYNTHETIC-AOC", kind: "ORGANIZATION" },
    sourceSnapshots: [{
      sourceSnapshotId: "SOURCE-SYNTHETIC-OPS-AOC",
      sourceHash: SYNTHETIC_SOURCE_HASH,
      clauseIds: ["CLAUSE-SYNTHETIC-OPS-AOC-1"],
      clauseLocators: ["Synthetic OPS/AOC 1"],
    }],
    secondaryCrosswalkPartition: {
      partitionId: "PARTITION-SYNTHETIC-INPUT",
      stableRowIds: ["CC:SYNTHETIC:OPS:AOC:1"],
    },
    unresolvedSourceGaps: [],
    generationPolicyVersion: "regulatory-checklist-v1",
    providerId: "deterministic-regulatory-fixture",
    providerVersion: "1.0.0",
    requestedOutputs: ["COMPLIANCE_MAPPING", "INSPECTION_CHECKLIST"],
    canonicalInputDigest: SYNTHETIC_INPUT_DIGEST,
  },
  inputDigest: SYNTHETIC_INPUT_DIGEST,
  outputDigest: SYNTHETIC_OUTPUT_DIGEST,
  sourceCurrentness: {
    currentSourceSnapshotId: "SOURCE-SYNTHETIC-OPS-AOC",
    currentSourceHash: SYNTHETIC_SOURCE_HASH,
    previousSourceSnapshotId: null,
    previousSourceHash: null,
  },
  complianceMappings: [{
    mappingId: "MAP-SYNTHETIC-OPS-AOC-001",
    requirement: "Synthetic controlled training requirement for verifying ramp safety evidence.",
    relationship: "ADDRESSES",
    applicability: "DIRECT",
    citations: [{
      sourceSnapshotId: "SOURCE-SYNTHETIC-OPS-AOC",
      sourceHash: SYNTHETIC_SOURCE_HASH,
      clauseId: "CLAUSE-SYNTHETIC-OPS-AOC-1",
      locator: "Synthetic OPS/AOC 1",
    }],
    sourceGap: null,
    rationale: "This synthetic source is test-profile-only and proves the bounded import workflow without asserting real authority.",
  }],
  inspectionChecklist: {
    checklistId: "CHK-SYNTHETIC-OPS-AOC-001",
    questions: [{
      questionId: "Q-SYNTHETIC-OPS-AOC-001",
      mappingIds: ["MAP-SYNTHETIC-OPS-AOC-001"],
      prompt: "Can the inspector reconcile the synthetic ramp-safety evidence with the controlled synthetic requirement?",
      citations: [{
        sourceSnapshotId: "SOURCE-SYNTHETIC-OPS-AOC",
        sourceHash: SYNTHETIC_SOURCE_HASH,
        clauseId: "CLAUSE-SYNTHETIC-OPS-AOC-1",
        locator: "Synthetic OPS/AOC 1",
      }],
      verificationMethod: "Physical observation and controlled-record reconciliation",
      expectedEvidence: ["Synthetic inspection observation", "Synthetic controlled record"],
      allowedAnswers: ["COMPLIANT", "NON_COMPLIANT", "OBSERVATION", "NOT_APPLICABLE", "NOT_CHECKED"],
      mandatoryCore: true,
      safetyCritical: true,
      origin: "REGULATORY_TRACE",
      scopeRecommendation: {
        classification: "MANDATORY_CORE",
        inputSignals: [
          "Mandatory synthetic safety-control configuration.",
          "No validated operational history is available for automatic deferral.",
        ],
        operationalHistoryBasis: "SYNTHETIC_UNKNOWN_HISTORY",
        rationale: "The synthetic mandatory safety control remains included pending Department Manager review.",
        guardrails: {
          mandatoryControl: true,
          safetyCritical: true,
          unknownHistory: true,
          sourceChanged: false,
          overdueControl: false,
          automaticDeferralPermitted: false,
        },
        approvalReviewState: "TECHNICAL_REVIEW_REQUIRED",
        automaticDeferral: false,
      },
      regulatoryTrace: {
        state: "RESOLVED",
        mappingReviewState: "SOURCE_OWNER_REVIEW_REQUIRED",
        sourceIdentity: "SYNTHETIC-OPS-AOC",
        sourceTitle: "Synthetic test-profile source",
        immutableVersion: "1",
        sha256: SYNTHETIC_SOURCE_HASH,
        locator: "Synthetic OPS/AOC 1",
        page: "1",
        section: "Synthetic OPS/AOC",
        clause: "CLAUSE-SYNTHETIC-OPS-AOC-1",
        sourceType: "SYNTHETIC_INTERNAL_TEST_PROFILE",
        applicability: "DIRECT",
        nationalReference: "Synthetic NAMCAR OPS/AOC reference",
        controlledCaaProcedureMapping: "Synthetic CAA ramp-inspection procedure mapping",
        verificationObjective: "Verify the controlled synthetic ramp-safety requirement through observation and record reconciliation.",
        expectedEvidence: ["Synthetic inspection observation", "Synthetic controlled record"],
        currentnessState: "CURRENT",
        technicalReviewState: "TECHNICAL_REVIEW_REQUIRED",
      },
      reconciliation: null,
    }],
  },
};

// Candidate-only legacy checklist input. This fixture intentionally has no
// citation or partial trace for its question: SOURCE_MAPPING_REQUIRED is the
// only permitted Draft repair state and is never an authority claim.
export const SYNTHETIC_LEGACY_CHECKLIST_CANDIDATE_BUNDLE: GovernedCandidateBundleInput = {
  schemaVersion: "1.0.0",
  candidateBundleId: "CAND-SYNTHETIC-LEGACY-CHECKLIST-0003",
  generationRunId: "GENRUN-SYNTHETIC-LEGACY-CHECKLIST-0003",
  status: "GENERATED_DRAFT",
  generationRequest: {
    schemaVersion: "1.0.0",
    requestId: "GENREQ-SYNTHETIC-LEGACY-CHECKLIST-0003",
    organizationId: "ORG-SYNTHETIC-AOC",
    serviceProviderScopeFactIds: ["SCOPE-SYNTHETIC-AOC"],
    serviceProviderTypes: ["AIR_OPERATOR"],
    providerCatalogVersion: "1.0.0",
    inspectionType: "RAMP_INSPECTION",
    target: { targetId: "TARGET-SYNTHETIC-AOC", kind: "ORGANIZATION" },
    sourceSnapshots: [{
      sourceSnapshotId: "SOURCE-SYNTHETIC-OPS-AOC",
      sourceHash: SYNTHETIC_SOURCE_HASH,
      clauseIds: ["CLAUSE-SYNTHETIC-OPS-AOC-1"],
      clauseLocators: ["Synthetic OPS/AOC 1"],
    }],
    secondaryCrosswalkPartition: {
      partitionId: "PARTITION-SYNTHETIC-INPUT",
      stableRowIds: ["CC:SYNTHETIC:OPS:AOC:1"],
    },
    unresolvedSourceGaps: [],
    generationPolicyVersion: "regulatory-checklist-v1",
    providerId: "deterministic-regulatory-fixture",
    providerVersion: "1.0.0",
    requestedOutputs: ["COMPLIANCE_MAPPING", "INSPECTION_CHECKLIST"],
    canonicalInputDigest: "sha256:5991bdb521a2e3385f94f282027670e914a5935e5a40e0a9b1daf87172573f3c",
  },
  inputDigest: "sha256:5991bdb521a2e3385f94f282027670e914a5935e5a40e0a9b1daf87172573f3c",
  outputDigest: "sha256:1c1cee0ca367092d54c80d1fce792fe3613c52bfec1aa64e3e708e390c1a0ba6",
  complianceMappings: [{
    mappingId: "MAP-SYNTHETIC-LEGACY-CANDIDATE-003",
    requirement: "Synthetic controlled training requirement for verifying ramp safety evidence.",
    relationship: "ADDRESSES",
    applicability: "DIRECT",
    citations: [{
      sourceSnapshotId: "SOURCE-SYNTHETIC-OPS-AOC",
      sourceHash: SYNTHETIC_SOURCE_HASH,
      clauseId: "CLAUSE-SYNTHETIC-OPS-AOC-1",
      locator: "Synthetic OPS/AOC 1",
    }],
    sourceGap: null,
    rationale: "This synthetic source is test-profile-only and proves the bounded import workflow without asserting real authority.",
  }],
  inspectionChecklist: {
    checklistId: "CHK-SYNTHETIC-LEGACY-CHECKLIST-003",
    questions: [{
      questionId: "Q-SYNTHETIC-LEGACY-CANDIDATE-003",
      mappingIds: ["MAP-SYNTHETIC-LEGACY-CANDIDATE-003"],
      prompt: "Historical checklist candidate: is the cabin/ramp safety control recorded for later source mapping?",
      citations: [],
      verificationMethod: "Historical candidate review only; no validation or execution claim",
      expectedEvidence: ["Synthetic historical checklist wording", "Synthetic historical result record"],
      allowedAnswers: ["COMPLIANT", "NON_COMPLIANT", "OBSERVATION", "NOT_APPLICABLE", "NOT_CHECKED"],
      mandatoryCore: false,
      safetyCritical: false,
      origin: "EXISTING_CHECKLIST_CANDIDATE",
      scopeRecommendation: {
        classification: "FOCUSED_FULL",
        inputSignals: [
          "Historical checklist wording is candidate input only.",
          "Unknown result-history quality prevents automatic deferral.",
        ],
        operationalHistoryBasis: "SYNTHETIC_LEGACY_HISTORY_UNKNOWN",
        rationale: "Keep the legacy candidate visible for Department Manager repair; it cannot establish regulatory applicability.",
        guardrails: {
          mandatoryControl: false,
          safetyCritical: false,
          unknownHistory: true,
          sourceChanged: false,
          overdueControl: false,
          automaticDeferralPermitted: false,
        },
        approvalReviewState: "TECHNICAL_REVIEW_REQUIRED",
        automaticDeferral: false,
      },
      regulatoryTrace: {
        state: "SOURCE_MAPPING_REQUIRED",
        mappingReviewState: "SOURCE_MAPPING_REQUIRED",
        technicalReviewState: "NOT_AVAILABLE",
      },
      reconciliation: null,
    }],
  },
};

// This separate new Draft binds the legacy candidate comparison to the current
// approved synthetic source chain. The prior wording/history remains visible
// only as candidate input; it does not supply the question's authority.
export const SYNTHETIC_HYBRID_RECONCILED_BUNDLE: GovernedCandidateBundleInput = {
  schemaVersion: "1.0.0",
  candidateBundleId: "CAND-SYNTHETIC-HYBRID-RECONCILED-0004",
  generationRunId: "GENRUN-SYNTHETIC-HYBRID-RECONCILED-0004",
  status: "GENERATED_DRAFT",
  generationRequest: {
    schemaVersion: "1.0.0",
    requestId: "GENREQ-SYNTHETIC-HYBRID-RECONCILED-0004",
    organizationId: "ORG-SYNTHETIC-AOC",
    serviceProviderScopeFactIds: ["SCOPE-SYNTHETIC-AOC"],
    serviceProviderTypes: ["AIR_OPERATOR"],
    providerCatalogVersion: "1.0.0",
    inspectionType: "RAMP_INSPECTION",
    target: { targetId: "TARGET-SYNTHETIC-AOC", kind: "ORGANIZATION" },
    sourceSnapshots: [{
      sourceSnapshotId: "SOURCE-SYNTHETIC-OPS-AOC-IMPACT-V2",
      sourceHash: "sha256:4444444444444444444444444444444444444444444444444444444444444444",
      clauseIds: ["CLAUSE-SYNTHETIC-OPS-AOC-IMPACT-2"],
      clauseLocators: ["Synthetic OPS/AOC impact 2"],
    }],
    secondaryCrosswalkPartition: {
      partitionId: "PARTITION-SYNTHETIC-IMPACT-INPUT",
      stableRowIds: ["CC:SYNTHETIC:OPS:AOC:IMPACT:2"],
    },
    unresolvedSourceGaps: [],
    generationPolicyVersion: "regulatory-checklist-v1",
    providerId: "deterministic-regulatory-fixture",
    providerVersion: "1.0.0",
    requestedOutputs: ["COMPLIANCE_MAPPING", "INSPECTION_CHECKLIST"],
    canonicalInputDigest: "sha256:9427a6c6bd7460ed0091746357d950fa32caf4d20d260b10732cbcd04a043159",
  },
  inputDigest: "sha256:9427a6c6bd7460ed0091746357d950fa32caf4d20d260b10732cbcd04a043159",
  outputDigest: "sha256:2b4ec73af67a5bacebf7397982079ff28c5f4d0493f3ac2cdc5d73ad3b2e3eba",
  sourceCurrentness: {
    currentSourceSnapshotId: "SOURCE-SYNTHETIC-OPS-AOC-IMPACT-V2",
    currentSourceHash: "sha256:4444444444444444444444444444444444444444444444444444444444444444",
    previousSourceSnapshotId: "SOURCE-SYNTHETIC-OPS-AOC",
    previousSourceHash: SYNTHETIC_SOURCE_HASH,
  },
  complianceMappings: [{
    mappingId: "MAP-SYNTHETIC-HYBRID-RECONCILED-004",
    requirement: "Synthetic controlled training requirement for verifying ramp safety evidence.",
    relationship: "ADDRESSES",
    applicability: "DIRECT",
    citations: [{
      sourceSnapshotId: "SOURCE-SYNTHETIC-OPS-AOC-IMPACT-V2",
      sourceHash: "sha256:4444444444444444444444444444444444444444444444444444444444444444",
      clauseId: "CLAUSE-SYNTHETIC-OPS-AOC-IMPACT-2",
      locator: "Synthetic OPS/AOC impact 2",
    }],
    sourceGap: null,
    rationale: "This synthetic source is test-profile-only and proves the bounded import workflow without asserting real authority.",
  }],
  inspectionChecklist: {
    checklistId: "CHK-SYNTHETIC-HYBRID-RECONCILED-004",
    questions: [{
      questionId: "Q-SYNTHETIC-HYBRID-RECONCILED-004",
      mappingIds: ["MAP-SYNTHETIC-HYBRID-RECONCILED-004"],
      prompt: "Can the inspector reconcile the synthetic ramp-safety evidence with the controlled synthetic requirement?",
      citations: [{
        sourceSnapshotId: "SOURCE-SYNTHETIC-OPS-AOC-IMPACT-V2",
        sourceHash: "sha256:4444444444444444444444444444444444444444444444444444444444444444",
        clauseId: "CLAUSE-SYNTHETIC-OPS-AOC-IMPACT-2",
        locator: "Synthetic OPS/AOC impact 2",
      }],
      verificationMethod: "Physical observation and controlled-record reconciliation",
      expectedEvidence: ["Synthetic inspection observation", "Synthetic controlled record"],
      allowedAnswers: ["COMPLIANT", "NON_COMPLIANT", "OBSERVATION", "NOT_APPLICABLE", "NOT_CHECKED"],
      mandatoryCore: false,
      safetyCritical: false,
      origin: "HYBRID_RECONCILED",
      scopeRecommendation: {
        classification: "ROTATIONAL_SAMPLE",
        inputSignals: [
          "Legacy checklist candidate was reconciled against the current synthetic controlled source chain.",
          "The controlled source changed, so the sampled control cannot be automatically deferred.",
        ],
        operationalHistoryBasis: "SYNTHETIC_LEGACY_CANDIDATE_RECONCILED",
        rationale: "Use a rotational sample only with Department Manager technical approval; the current trace, not historical wording, is authoritative.",
        guardrails: {
          mandatoryControl: false,
          safetyCritical: false,
          unknownHistory: false,
          sourceChanged: true,
          overdueControl: false,
          automaticDeferralPermitted: false,
        },
        approvalReviewState: "TECHNICAL_REVIEW_REQUIRED",
        automaticDeferral: false,
      },
      regulatoryTrace: {
        state: "RESOLVED",
        mappingReviewState: "SOURCE_OWNER_REVIEW_REQUIRED",
        sourceIdentity: "SYNTHETIC-OPS-AOC",
        sourceTitle: "Synthetic test-profile impact source",
        immutableVersion: "2",
        sha256: "sha256:4444444444444444444444444444444444444444444444444444444444444444",
        locator: "Synthetic OPS/AOC impact 2",
        page: "2",
        section: "Synthetic OPS/AOC impact",
        clause: "CLAUSE-SYNTHETIC-OPS-AOC-IMPACT-2",
        sourceType: "SYNTHETIC_INTERNAL_TEST_PROFILE",
        applicability: "DIRECT",
        nationalReference: "Synthetic NAMCAR OPS/AOC impact reference",
        controlledCaaProcedureMapping: "Synthetic CAA ramp-inspection procedure impact mapping",
        verificationObjective: "Verify the controlled synthetic ramp-safety requirement through observation and record reconciliation.",
        expectedEvidence: ["Synthetic inspection observation", "Synthetic controlled record"],
        currentnessState: "CURRENT",
        technicalReviewState: "TECHNICAL_REVIEW_REQUIRED",
      },
      reconciliation: {
        legacyQuestionId: "Q-SYNTHETIC-LEGACY-CANDIDATE-003",
        legacyWording: "Historical checklist candidate: is the cabin/ramp safety control recorded for later source mapping?",
        legacyOperationalIntent: "Preserve a cabin/ramp safety observation as a candidate input for a future controlled mapping.",
        legacyResultHistory: "Synthetic historical outcome record is unverified candidate input and does not establish a clean-history window.",
        legacyExpectedEvidence: ["Synthetic historical checklist wording", "Synthetic historical result record"],
        legacyApplicability: "UNKNOWN_CANDIDATE_INPUT",
        legacyScopeClassification: "UNKNOWN_CANDIDATE_INPUT",
        currentWording: "Can the inspector reconcile the synthetic ramp-safety evidence with the controlled synthetic requirement?",
        currentExpectedEvidence: ["Synthetic inspection observation", "Synthetic controlled record"],
        currentApplicability: "DIRECT",
        currentScopeClassification: "ROTATIONAL_SAMPLE",
        wordingChanged: true,
        evidenceChanged: true,
        applicabilityChanged: true,
        scopeChanged: true,
      },
    }],
  },
};
