// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeDelivery = `-- name: AcknowledgeDelivery :one
UPDATE datafeed_delivery_state
SET status = 'ACKNOWLEDGED', acknowledgement_receipt_digest = $1,
    acknowledged_at = $2, terminal_outcome_code = $3,
    lease_expires_at = NULL, updated_at = $2
WHERE event_id = $4
  AND status = 'LEASED'
  AND lease_generation = $5
RETURNING event_id, lease_generation, status, acknowledgement_receipt_digest, acknowledged_at
`

type AcknowledgeDeliveryParams struct {
	ReceiptDigest       *string            `json:"receipt_digest"`
	AcknowledgedAt      pgtype.Timestamptz `json:"acknowledged_at"`
	TerminalOutcomeCode *string            `json:"terminal_outcome_code"`
	EventID             pgtype.UUID        `json:"event_id"`
	LeaseGeneration     int64              `json:"lease_generation"`
}

type AcknowledgeDeliveryRow struct {
	EventID                      pgtype.UUID        `json:"event_id"`
	LeaseGeneration              int64              `json:"lease_generation"`
	Status                       string             `json:"status"`
	AcknowledgementReceiptDigest *string            `json:"acknowledgement_receipt_digest"`
	AcknowledgedAt               pgtype.Timestamptz `json:"acknowledged_at"`
}

func (q *Queries) AcknowledgeDelivery(ctx context.Context, arg AcknowledgeDeliveryParams) (AcknowledgeDeliveryRow, error) {
	row := q.db.QueryRow(ctx, acknowledgeDelivery,
		arg.ReceiptDigest,
		arg.AcknowledgedAt,
		arg.TerminalOutcomeCode,
		arg.EventID,
		arg.LeaseGeneration,
	)
	var i AcknowledgeDeliveryRow
	err := row.Scan(
		&i.EventID,
		&i.LeaseGeneration,
		&i.Status,
		&i.AcknowledgementReceiptDigest,
		&i.AcknowledgedAt,
	)
	return i, err
}

const appendDeliveryAttempt = `-- name: AppendDeliveryAttempt :exec
INSERT INTO datafeed_delivery_attempts (
    attempt_id, event_id, lease_generation, outcome_code,
    acknowledgement_receipt_digest, diagnostic_code, occurred_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
`

type AppendDeliveryAttemptParams struct {
	AttemptID                    pgtype.UUID        `json:"attempt_id"`
	EventID                      pgtype.UUID        `json:"event_id"`
	LeaseGeneration              int64              `json:"lease_generation"`
	OutcomeCode                  string             `json:"outcome_code"`
	AcknowledgementReceiptDigest *string            `json:"acknowledgement_receipt_digest"`
	DiagnosticCode               *string            `json:"diagnostic_code"`
	OccurredAt                   pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) AppendDeliveryAttempt(ctx context.Context, arg AppendDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, appendDeliveryAttempt,
		arg.AttemptID,
		arg.EventID,
		arg.LeaseGeneration,
		arg.OutcomeCode,
		arg.AcknowledgementReceiptDigest,
		arg.DiagnosticCode,
		arg.OccurredAt,
	)
	return err
}

const claimPendingDelivery = `-- name: ClaimPendingDelivery :many
WITH eligible AS (
    SELECT state.event_id, event.occurred_at
    FROM datafeed_delivery_state state
    JOIN datafeed_events event ON event.event_id = state.event_id
    LEFT JOIN datafeed_replay_tombstones tombstone ON tombstone.event_id = event.event_id
    WHERE event.tenant_id = $3
      AND event.owning_organization_id = $4
      AND tombstone.event_id IS NULL
      AND (
            (state.status = 'PENDING' AND (state.next_attempt_at IS NULL OR state.next_attempt_at <= $2))
         OR (state.status = 'LEASED' AND state.lease_expires_at <= $2)
      )
    ORDER BY event.occurred_at, event.event_id
    LIMIT $5
    FOR UPDATE OF state SKIP LOCKED
)
UPDATE datafeed_delivery_state state
SET status = 'LEASED', lease_generation = state.lease_generation + 1,
    lease_expires_at = $1, updated_at = $2
FROM eligible
WHERE state.event_id = eligible.event_id
RETURNING state.event_id, state.lease_generation, state.lease_expires_at, state.attempt_count, eligible.occurred_at
`

type ClaimPendingDeliveryParams struct {
	LeaseExpiresAt       pgtype.Timestamptz `json:"lease_expires_at"`
	NowAt                pgtype.Timestamptz `json:"now_at"`
	TenantID             string             `json:"tenant_id"`
	OwningOrganizationID string             `json:"owning_organization_id"`
	LimitCount           int32              `json:"limit_count"`
}

type ClaimPendingDeliveryRow struct {
	EventID         pgtype.UUID        `json:"event_id"`
	LeaseGeneration int64              `json:"lease_generation"`
	LeaseExpiresAt  pgtype.Timestamptz `json:"lease_expires_at"`
	AttemptCount    int32              `json:"attempt_count"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) ClaimPendingDelivery(ctx context.Context, arg ClaimPendingDeliveryParams) ([]ClaimPendingDeliveryRow, error) {
	rows, err := q.db.Query(ctx, claimPendingDelivery,
		arg.LeaseExpiresAt,
		arg.NowAt,
		arg.TenantID,
		arg.OwningOrganizationID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingDeliveryRow
	for rows.Next() {
		var i ClaimPendingDeliveryRow
		if err := rows.Scan(
			&i.EventID,
			&i.LeaseGeneration,
			&i.LeaseExpiresAt,
			&i.AttemptCount,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventForScopedPublication = `-- name: GetEventForScopedPublication :one
SELECT event_id, contract_id, contract_version, schema_version, event_type, event_version,
       source_module, source_system, tenant_id, owning_organization_id,
       actor_organization_id, visibility_purpose_code, canonical_event_sha256,
       payload_ciphertext, payload_nonce, payload_key_ref, payload_sha256,
       entity_refs, state_before, state_after, effective_at,
       known_at, occurred_at, emitted_at, aggregate_type, aggregate_id,
       aggregate_revision, correlation_id, causation_id
FROM datafeed_events
WHERE event_id = $1
  AND tenant_id = $2
  AND owning_organization_id = $3
`

type GetEventForScopedPublicationParams struct {
	EventID              pgtype.UUID `json:"event_id"`
	TenantID             string      `json:"tenant_id"`
	OwningOrganizationID string      `json:"owning_organization_id"`
}

type GetEventForScopedPublicationRow struct {
	EventID               pgtype.UUID        `json:"event_id"`
	ContractID            string             `json:"contract_id"`
	ContractVersion       string             `json:"contract_version"`
	SchemaVersion         string             `json:"schema_version"`
	EventType             string             `json:"event_type"`
	EventVersion          int32              `json:"event_version"`
	SourceModule          string             `json:"source_module"`
	SourceSystem          string             `json:"source_system"`
	TenantID              string             `json:"tenant_id"`
	OwningOrganizationID  string             `json:"owning_organization_id"`
	ActorOrganizationID   *string            `json:"actor_organization_id"`
	VisibilityPurposeCode string             `json:"visibility_purpose_code"`
	CanonicalEventSha256  string             `json:"canonical_event_sha256"`
	PayloadCiphertext     []byte             `json:"payload_ciphertext"`
	PayloadNonce          []byte             `json:"payload_nonce"`
	PayloadKeyRef         string             `json:"payload_key_ref"`
	PayloadSha256         string             `json:"payload_sha256"`
	EntityRefs            []byte             `json:"entity_refs"`
	StateBefore           *string            `json:"state_before"`
	StateAfter            string             `json:"state_after"`
	EffectiveAt           pgtype.Timestamptz `json:"effective_at"`
	KnownAt               pgtype.Timestamptz `json:"known_at"`
	OccurredAt            pgtype.Timestamptz `json:"occurred_at"`
	EmittedAt             pgtype.Timestamptz `json:"emitted_at"`
	AggregateType         string             `json:"aggregate_type"`
	AggregateID           string             `json:"aggregate_id"`
	AggregateRevision     int64              `json:"aggregate_revision"`
	CorrelationID         pgtype.UUID        `json:"correlation_id"`
	CausationID           pgtype.UUID        `json:"causation_id"`
}

func (q *Queries) GetEventForScopedPublication(ctx context.Context, arg GetEventForScopedPublicationParams) (GetEventForScopedPublicationRow, error) {
	row := q.db.QueryRow(ctx, getEventForScopedPublication, arg.EventID, arg.TenantID, arg.OwningOrganizationID)
	var i GetEventForScopedPublicationRow
	err := row.Scan(
		&i.EventID,
		&i.ContractID,
		&i.ContractVersion,
		&i.SchemaVersion,
		&i.EventType,
		&i.EventVersion,
		&i.SourceModule,
		&i.SourceSystem,
		&i.TenantID,
		&i.OwningOrganizationID,
		&i.ActorOrganizationID,
		&i.VisibilityPurposeCode,
		&i.CanonicalEventSha256,
		&i.PayloadCiphertext,
		&i.PayloadNonce,
		&i.PayloadKeyRef,
		&i.PayloadSha256,
		&i.EntityRefs,
		&i.StateBefore,
		&i.StateAfter,
		&i.EffectiveAt,
		&i.KnownAt,
		&i.OccurredAt,
		&i.EmittedAt,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateRevision,
		&i.CorrelationID,
		&i.CausationID,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO datafeed_events (
    event_id, contract_id, contract_version, schema_version, event_type,
    event_version, source_module, source_system, tenant_id,
    owning_organization_id, actor_organization_id, visibility_purpose_code,
    operation_id, correlation_id, causation_id, aggregate_type, aggregate_id,
    aggregate_revision, effective_at, known_at, occurred_at, emitted_at,
    entity_refs, state_before, state_after, privacy_class, payload_ciphertext,
    payload_nonce, payload_key_ref, payload_sha256, canonical_event_sha256
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11,
    $12, $13,
    $14, $15, $16,
    $17, $18, $19,
    $20, $21, $22,
    $23, $24, $25,
    $26, $27, $28,
    $29, $30, $31
)
RETURNING event_id, created_at
`

type InsertEventParams struct {
	EventID               pgtype.UUID        `json:"event_id"`
	ContractID            string             `json:"contract_id"`
	ContractVersion       string             `json:"contract_version"`
	SchemaVersion         string             `json:"schema_version"`
	EventType             string             `json:"event_type"`
	EventVersion          int32              `json:"event_version"`
	SourceModule          string             `json:"source_module"`
	SourceSystem          string             `json:"source_system"`
	TenantID              string             `json:"tenant_id"`
	OwningOrganizationID  string             `json:"owning_organization_id"`
	ActorOrganizationID   *string            `json:"actor_organization_id"`
	VisibilityPurposeCode string             `json:"visibility_purpose_code"`
	OperationID           string             `json:"operation_id"`
	CorrelationID         pgtype.UUID        `json:"correlation_id"`
	CausationID           pgtype.UUID        `json:"causation_id"`
	AggregateType         string             `json:"aggregate_type"`
	AggregateID           string             `json:"aggregate_id"`
	AggregateRevision     int64              `json:"aggregate_revision"`
	EffectiveAt           pgtype.Timestamptz `json:"effective_at"`
	KnownAt               pgtype.Timestamptz `json:"known_at"`
	OccurredAt            pgtype.Timestamptz `json:"occurred_at"`
	EmittedAt             pgtype.Timestamptz `json:"emitted_at"`
	EntityRefs            []byte             `json:"entity_refs"`
	StateBefore           *string            `json:"state_before"`
	StateAfter            string             `json:"state_after"`
	PrivacyClass          string             `json:"privacy_class"`
	PayloadCiphertext     []byte             `json:"payload_ciphertext"`
	PayloadNonce          []byte             `json:"payload_nonce"`
	PayloadKeyRef         string             `json:"payload_key_ref"`
	PayloadSha256         string             `json:"payload_sha256"`
	CanonicalEventSha256  string             `json:"canonical_event_sha256"`
}

type InsertEventRow struct {
	EventID   pgtype.UUID        `json:"event_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.EventID,
		arg.ContractID,
		arg.ContractVersion,
		arg.SchemaVersion,
		arg.EventType,
		arg.EventVersion,
		arg.SourceModule,
		arg.SourceSystem,
		arg.TenantID,
		arg.OwningOrganizationID,
		arg.ActorOrganizationID,
		arg.VisibilityPurposeCode,
		arg.OperationID,
		arg.CorrelationID,
		arg.CausationID,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateRevision,
		arg.EffectiveAt,
		arg.KnownAt,
		arg.OccurredAt,
		arg.EmittedAt,
		arg.EntityRefs,
		arg.StateBefore,
		arg.StateAfter,
		arg.PrivacyClass,
		arg.PayloadCiphertext,
		arg.PayloadNonce,
		arg.PayloadKeyRef,
		arg.PayloadSha256,
		arg.CanonicalEventSha256,
	)
	var i InsertEventRow
	err := row.Scan(&i.EventID, &i.CreatedAt)
	return i, err
}

const quarantineDelivery = `-- name: QuarantineDelivery :one
UPDATE datafeed_delivery_state
SET status = 'QUARANTINED', lease_expires_at = NULL,
    quarantine_owner_role = $1,
    quarantine_sla_due_at = $2,
    terminal_outcome_code = $3, updated_at = $4
WHERE event_id = $5
  AND status = 'LEASED'
  AND lease_generation = $6
RETURNING event_id, lease_generation, status, terminal_outcome_code
`

type QuarantineDeliveryParams struct {
	QuarantineOwnerRole *string            `json:"quarantine_owner_role"`
	QuarantineSlaDueAt  pgtype.Timestamptz `json:"quarantine_sla_due_at"`
	OutcomeCode         *string            `json:"outcome_code"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	EventID             pgtype.UUID        `json:"event_id"`
	LeaseGeneration     int64              `json:"lease_generation"`
}

type QuarantineDeliveryRow struct {
	EventID             pgtype.UUID `json:"event_id"`
	LeaseGeneration     int64       `json:"lease_generation"`
	Status              string      `json:"status"`
	TerminalOutcomeCode *string     `json:"terminal_outcome_code"`
}

func (q *Queries) QuarantineDelivery(ctx context.Context, arg QuarantineDeliveryParams) (QuarantineDeliveryRow, error) {
	row := q.db.QueryRow(ctx, quarantineDelivery,
		arg.QuarantineOwnerRole,
		arg.QuarantineSlaDueAt,
		arg.OutcomeCode,
		arg.UpdatedAt,
		arg.EventID,
		arg.LeaseGeneration,
	)
	var i QuarantineDeliveryRow
	err := row.Scan(
		&i.EventID,
		&i.LeaseGeneration,
		&i.Status,
		&i.TerminalOutcomeCode,
	)
	return i, err
}

const retryDelivery = `-- name: RetryDelivery :one
UPDATE datafeed_delivery_state
SET status = 'PENDING', lease_expires_at = NULL, next_attempt_at = $1,
    attempt_count = attempt_count + 1, terminal_outcome_code = $2,
    updated_at = $3
WHERE event_id = $4
  AND status = 'LEASED'
  AND lease_generation = $5
RETURNING event_id, lease_generation, status, attempt_count, next_attempt_at
`

type RetryDeliveryParams struct {
	NextAttemptAt   pgtype.Timestamptz `json:"next_attempt_at"`
	OutcomeCode     *string            `json:"outcome_code"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	EventID         pgtype.UUID        `json:"event_id"`
	LeaseGeneration int64              `json:"lease_generation"`
}

type RetryDeliveryRow struct {
	EventID         pgtype.UUID        `json:"event_id"`
	LeaseGeneration int64              `json:"lease_generation"`
	Status          string             `json:"status"`
	AttemptCount    int32              `json:"attempt_count"`
	NextAttemptAt   pgtype.Timestamptz `json:"next_attempt_at"`
}

func (q *Queries) RetryDelivery(ctx context.Context, arg RetryDeliveryParams) (RetryDeliveryRow, error) {
	row := q.db.QueryRow(ctx, retryDelivery,
		arg.NextAttemptAt,
		arg.OutcomeCode,
		arg.UpdatedAt,
		arg.EventID,
		arg.LeaseGeneration,
	)
	var i RetryDeliveryRow
	err := row.Scan(
		&i.EventID,
		&i.LeaseGeneration,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
	)
	return i, err
}
