// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	AcknowledgeDelivery(ctx context.Context, arg AcknowledgeDeliveryParams) (AcknowledgeDeliveryRow, error)
	AppendDeliveryAttempt(ctx context.Context, arg AppendDeliveryAttemptParams) error
	ClaimPendingDelivery(ctx context.Context, arg ClaimPendingDeliveryParams) ([]ClaimPendingDeliveryRow, error)
	GetEventForScopedPublication(ctx context.Context, arg GetEventForScopedPublicationParams) (GetEventForScopedPublicationRow, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error)
	QuarantineDelivery(ctx context.Context, arg QuarantineDeliveryParams) (QuarantineDeliveryRow, error)
	RetryDelivery(ctx context.Context, arg RetryDeliveryParams) (RetryDeliveryRow, error)
}

var _ Querier = (*Queries)(nil)
