-- Candidate-only, forward-only projection of the source auth schema.
-- Execute exactly once in lexical order. This compact migration is derived
-- from source migrations 001, 006, 010, 011, 015, 017, and 035. It contains
-- only columns and constraints required by the exported auth package and is
-- not byte-for-byte identical to any one source-repository migration.

CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    name TEXT NOT NULL DEFAULT '',
    surname TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'member',
    picture_url TEXT NOT NULL DEFAULT '',
    raw JSONB NOT NULL DEFAULT '{}'::jsonb,
    account_status TEXT NOT NULL DEFAULT 'active'
        CHECK (account_status IN ('active', 'deletion_pending', 'deleted_tombstone')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.cities (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    raw JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.auth_accounts (
    user_id BIGINT PRIMARY KEY REFERENCES app.users(id) ON DELETE CASCADE,
    subject TEXT NOT NULL,
    username TEXT NOT NULL,
    email TEXT NOT NULL DEFAULT '',
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member',
    auth_version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_accounts_subject
    ON app.auth_accounts (subject);

CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_accounts_username
    ON app.auth_accounts (lower(username));

CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_accounts_email
    ON app.auth_accounts (lower(email))
    WHERE email <> '';

CREATE TABLE IF NOT EXISTS app.auth_sessions (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,
    refresh_token_hash TEXT NOT NULL UNIQUE,
    user_agent TEXT NOT NULL DEFAULT '',
    device_id TEXT NOT NULL DEFAULT '',
    client_id TEXT NOT NULL DEFAULT '',
    platform TEXT NOT NULL DEFAULT '',
    app_version TEXT NOT NULL DEFAULT '',
    device_signal_hash TEXT NOT NULL DEFAULT '',
    auth_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    absolute_expires_at TIMESTAMPTZ NOT NULL,
    idle_expires_at TIMESTAMPTZ NOT NULL,
    last_step_up_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoked_by_user_id BIGINT REFERENCES app.users(id) ON DELETE SET NULL,
    revoked_reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_active
    ON app.auth_sessions (user_id, expires_at)
    WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_client_active
    ON app.auth_sessions (user_id, client_id, idle_expires_at)
    WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS app.auth_refresh_tokens (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id TEXT NOT NULL REFERENCES app.auth_sessions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,
    family_id TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    client_id TEXT NOT NULL DEFAULT '',
    device_signal_hash TEXT NOT NULL DEFAULT '',
    issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    idle_expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    rotated_at TIMESTAMPTZ,
    replaced_by_token_hash TEXT NOT NULL DEFAULT '',
    revoked_at TIMESTAMPTZ,
    revoked_reason TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_auth_refresh_tokens_session
    ON app.auth_refresh_tokens (session_id);

CREATE INDEX IF NOT EXISTS idx_auth_refresh_tokens_family
    ON app.auth_refresh_tokens (family_id);

CREATE INDEX IF NOT EXISTS idx_auth_refresh_tokens_active
    ON app.auth_refresh_tokens (user_id, expires_at, idle_expires_at)
    WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS app.auth_security_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT REFERENCES app.users(id) ON DELETE SET NULL,
    session_id TEXT REFERENCES app.auth_sessions(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    client_id TEXT NOT NULL DEFAULT '',
    ip_hash TEXT NOT NULL DEFAULT '',
    user_agent_hash TEXT NOT NULL DEFAULT '',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auth_security_events_user_time
    ON app.auth_security_events (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_auth_security_events_type_time
    ON app.auth_security_events (event_type, created_at DESC);

CREATE TABLE IF NOT EXISTS app.staff_permissions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,
    permission TEXT NOT NULL,
    scope TEXT NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT true,
    granted_by_user_id BIGINT REFERENCES app.users(id) ON DELETE SET NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at TIMESTAMPTZ,
    raw JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (user_id, permission, scope)
);

CREATE INDEX IF NOT EXISTS idx_staff_permissions_lookup
    ON app.staff_permissions (user_id, permission, active);

INSERT INTO app.schema_migrations (version)
VALUES ('001_auth_identity')
ON CONFLICT (version) DO NOTHING;
